name: Ontology Documentation CI

on: 
  push: 
      branches:
          - main
 
jobs:


  ontdocI:
    uses: sparqlunicorn/sparqlunicornGoesGIS-ontdoc/.github/workflows/udoc.yml@main
    name: Ontdoc I      
    with: 
          rdffilepath: signlist/signlist.ttl
          version: v017dev
          docpath: docs
          prefixns: https://situx.github.io/cuneiformontology/
          prefixnsshort: cunei
          indexpages: true
          metadatatable: true
          createcollections: true
          iiif: true
          createnonNSPages: true
          createVOWL: true
          preferredlang: en
          ghpages: true
          
  ontdocII:
      uses: sparqlunicorn/sparqlunicornGoesGIS-ontdoc/.github/workflows/udoc.yml@main
      name: Ontdoc II      
      with: 
            rdffilepath: merged.ttl
            version: v017dev
            docpath: docs
            prefixns: https://situx.github.io/cuneiformontology/
            prefixnsshort: cunei
            indexpages: true
            metadatatable: true
            createcollections: true
            iiif: true
            createnonNSPages: true
            createVOWL: true
            preferredlang: en
            ghpages: true

  
  build:

        runs-on: ubuntu-latest
        concurrency: ci-${{ github.ref }}
        #needs: [ontdocI,ontdocII] 
        steps:
        - uses: actions/checkout@v3
        - uses: actions/checkout@v3
          continue-on-error: true
          with:
              repository: sparqlunicorn/sparqlunicornGoesGIS-ontdoc
              ref: v017dev
              path: ontdocscript
        - name: Create Ontology Documentation 🔧
          run: |
             sudo apt-get install python3 python3-setuptools python3-pip -y
             sudo apt-get install gcc libpq-dev -y
             sudo apt-get install python3-dev python3-pip -y
             sudo apt-get install python3-venv python3-wheel -y
             sudo pip3 install wheel pylode==2.13.2 rdflib shapely pillow
             pylode -i ontmodel/cuneiformontology.ttl -o docs/ontology.html
             pylode -i ontmodel/imageannotation_vocab.ttl -o docs/imageannotation.html
             pylode -i interlinks/cuneiformontology_interlinks.ttl -o docs/ontologyinterlinks.html
             pylode -i signlist/signlist.ttl -o docs/signlist.html
             pylode -i postagging/akkadian.ttl -o docs/postagging_akkadian.html
             pylode -i postagging/hittite.ttl -o docs/postagging_hittite.html
             pylode -i examples/HS1174/ttl/hs1174.ttl -o docs/example_hs1174.html
             pylode -i examples/HT073195/ttl/ht073195.ttl -o docs/example_ht073195.html
             pylode -i examples/O147/ttl/o147.ttl -o docs/example_o147.html
             pylode -i examples/TCH92/ttl/tch92.ttl -o docs/example_tch92.html
             mkdir docs/examples/
             mkdir docs/examples/hs1174/
             mkdir docs/examples/ht073195/
             mkdir docs/examples/tch92/
             mkdir docs/examples/o147/
             mkdir docs/contexts/
             cp jtfcontext/jtfcontext.json docs/contexts/jtfld.json
             cp -r examples/HS1174/images/ docs/examples/hs1174/images/ 
             cp -r examples/HT073195/images/ docs/examples/ht073195/images/ 
             cp -r examples/TCH92/images/ docs/examples/tch92/images/ 
             cp -r examples/O147/images/ docs/examples/o147/images/ 
             #wget https://raw.githubusercontent.com/sparqlunicorn/sparqlunicornGoesGIS-ontdoc/main/docgeneration.py 
             #wget https://raw.githubusercontent.com/sparqlunicorn/sparqlunicornGoesGIS-ontdoc/main/prefixes.json 
             cd ontdocscript
             #python3 docgeneration.py --input ../signlist/signlist.ttl --output ../docs/ --prefixns https://situx.github.io/cuneiformontology/ --prefixnsshort cuneisignlist --metadatatable true --deploypath https://situx.github.io/cuneiformontology/
             #python3 docgeneration.py --input ../merged.ttl --output ../docs/ --prefixns https://situx.github.io/cuneiformontology/ --prefixnsshort cuneisignlist --metadatatable true --deploypath https://situx.github.io/cuneiformontology/
             #python3 docgeneration.py --input examples/HS1174/transliteration/HS1174.atf.ttl --output docs/ --prefixns https://situx.github.io/cuneiformontology/ --prefixnsshort cuneiex --metadatatable true --deploypath https://situx.github.io/cuneiformontology/
             #python3 docgeneration.py --input examples/HS1174/transliteration/HS1174_textanno.ttl --output docs/ --prefixns https://situx.github.io/cuneiformontology/ --prefixnsshort cuneiex --metadatatable true --deploypath https://situx.github.io/cuneiformontology/
             #python3 docgeneration.py --input examples/HS1174/ttl/hs1174.ttl --output docs/ --prefixns https://situx.github.io/cuneiformontology/ --prefixnsshort cuneiex --metadatatable true --deploypath https://situx.github.io/cuneiformontology/
             #python3 docgeneration.py --input examples/HS1174/ttl/HS1174_front.png.ttl --output docs/ --prefixns https://situx.github.io/cuneiformontology/ --prefixnsshort cuneiex --metadatatable true --deploypath https://situx.github.io/cuneiformontology/
             #python3 docgeneration.py --input examples/HS1174/ttl/HS1174_back.png.ttl --output docs/ --prefixns https://situx.github.io/cuneiformontology/ --prefixnsshort cuneiex --metadatatable true --deploypath https://situx.github.io/cuneiformontology/
             #python3 docgeneration.py --input examples/HS1174/ttl/HS1174_charvariant.ttl --output docs/ --prefixns https://situx.github.io/cuneiformontology/ --prefixnsshort cuneiex --metadatatable true --deploypath https://situx.github.io/cuneiformontology/
             #python3 docgeneration.py --input examples/HS1174/mesh/HS1174_mesh.ttl --output docs/ --prefixns https://situx.github.io/cuneiformontology/ --prefixnsshort cuneiex --metadatatable true --deploypath https://situx.github.io/cuneiformontology/
             #python3 docgeneration.py --input examples/HT073195/transliteration/HT073195.atf.ttl --output docs/ --prefixns https://situx.github.io/cuneiformontology/ --prefixnsshort cuneiex --metadatatable true --deploypath https://situx.github.io/cuneiformontology/
             #python3 docgeneration.py --input examples/HT073195/ttl/HT073195_front.png.ttl --output docs/ --prefixns https://situx.github.io/cuneiformontology/ --prefixnsshort cuneiex --metadatatable true --deploypath https://situx.github.io/cuneiformontology/
             #python3 docgeneration.py --input examples/HT073195/ttl/ht073195.ttl --output docs/ --prefixns https://situx.github.io/cuneiformontology/ --prefixnsshort cuneiex --metadatatable true --deploypath https://situx.github.io/cuneiformontology/
             #python3 docgeneration.py --input examples/HT073195/transliteration/HT073195_textanno.ttl --output docs/ --prefixns https://situx.github.io/cuneiformontology/ --prefixnsshort cuneiex --metadatatable true --deploypath https://situx.github.io/cuneiformontology/
             #python3 docgeneration.py --input examples/O147/transliteration/O147.atf.ttl --output docs/ --prefixns https://situx.github.io/cuneiformontology/ --prefixnsshort cuneiex --metadatatable true --deploypath https://situx.github.io/cuneiformontology/
             #python3 docgeneration.py --input examples/O147/ttl/O147_front.png.ttl --output docs/ --prefixns https://situx.github.io/cuneiformontology/ --prefixnsshort cuneiex --metadatatable true --deploypath https://situx.github.io/cuneiformontology/
             #python3 docgeneration.py --input examples/O147/ttl/o147.ttl --output docs/ --prefixns https://situx.github.io/cuneiformontology/ --prefixnsshort cuneiex --metadatatable true --deploypath https://situx.github.io/cuneiformontology/
             #python3 docgeneration.py --input examples/O147/ttl/O147_back.png.ttl --output docs/ --prefixns https://situx.github.io/cuneiformontology/ --prefixnsshort cuneiex --metadatatable true --deploypath https://situx.github.io/cuneiformontology/
             #python3 docgeneration.py --input examples/O147/ttl/O147_right.png.ttl --output docs/ --prefixns https://situx.github.io/cuneiformontology/ --prefixnsshort cuneiex --metadatatable true --deploypath https://situx.github.io/cuneiformontology/ 
             #python3 docgeneration.py --input examples/O147/ttl/O147_bottom.png.ttl --output docs/ --prefixns https://situx.github.io/cuneiformontology/ --prefixnsshort cuneiex --metadatatable true --deploypath https://situx.github.io/cuneiformontology/
             #python3 docgeneration.py --input examples/O147/mesh/O147_front_mesh.ttl --output docs/ --prefixns https://situx.github.io/cuneiformontology/ --prefixnsshort cuneiex --metadatatable true --deploypath https://situx.github.io/cuneiformontology/
             #python3 docgeneration.py --input examples/O147/mesh/O147_back_mesh.ttl --output docs/ --prefixns https://situx.github.io/cuneiformontology/ --prefixnsshort cuneiex --metadatatable true --deploypath https://situx.github.io/cuneiformontology/
             #python3 docgeneration.py --input examples/O147/transliteration/O147_textanno.ttl --output docs/ --prefixns https://situx.github.io/cuneiformontology/ --prefixnsshort cuneiex --metadatatable true --deploypath https://situx.github.io/cuneiformontology/
             #python3 docgeneration.py --input examples/TCH92//transliteration/TCH92.atf.ttl --output docs/ --prefixns https://situx.github.io/cuneiformontology/ --prefixnsshort cuneiex --metadatatable true --deploypath https://situx.github.io/cuneiformontology/
             #python3 docgeneration.py --input examples/TCH92/ttl/TCH92_front.png.ttl --output docs/ --prefixns https://situx.github.io/cuneiformontology/ --prefixnsshort cuneiex --metadatatable true --deploypath https://situx.github.io/cuneiformontology/
             #python3 docgeneration.py --input examples/TCH92/ttl/tch92.ttl --output docs/ --prefixns https://situx.github.io/cuneiformontology/ --prefixnsshort cuneiex --metadatatable true --deploypath https://situx.github.io/cuneiformontology/
             #python3 docgeneration.py --input examples/TCH92/transliteration/TCH92_textanno.ttl --output docs/ --prefixns https://situx.github.io/cuneiformontology/ --prefixnsshort cuneiex --metadatatable true --deploypath https://situx.github.io/cuneiformontology/
             #python3 docgeneration.py --input examples/TCH92/ttl/TCH92_back.png.ttl --output docs/ --prefixns https://situx.github.io/cuneiformontology/ --prefixnsshort cuneiex --metadatatable true --deploypath https://situx.github.io/cuneiformontology/
             #python3 docgeneration.py --input examples/TCH92/mesh/TCH92_mesh.ttl --output docs/ --prefixns https://situx.github.io/cuneiformontology/ --prefixnsshort cuneiex --metadatatable true --deploypath https://situx.github.io/cuneiformontology/
        - name: Deploy 🚀
          uses: JamesIves/github-pages-deploy-action@releases/v4
          with:
             BRANCH: gh-pages
             FOLDER: docs/
             clean: false
