name: Ontology Documentation CI

on: 
  push: 
      branches:
          - main
jobs:
  build:

    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Create Ontology Documentation 🔧
      run: |
         sudo apt-get install python3 python3-setuptools python3-pip -y
         sudo apt-get install gcc libpq-dev -y
         sudo apt-get install python-dev python3-pip -y
         sudo apt-get install asciidoctor ruby -y
         sudo gem install --pre asciidoctor-pdf
         sudo apt-get install python3-dev python3-pip python3-venv python3-wheel -y
         sudo pip3 install wheel pylode==2.13.2 rdflib
         pylode -i ontmodel/cuneiformontology.ttl -o docs/ontology.html
         pylode -i interlinks/cuneiformontology_interlinks.ttl -o docs/ontologyinterlinks.html
         pylode -i postagging/akkadian.ttl -o docs/postagging_akkadian.html
         pylode -i postagging/hittite.ttl -o docs/postagging_hittite.html
         pylode -i examples/HS1174/ttl/hs1174.ttl -o docs/example_hs1174.html
         pylode -i examples/examples/HT073195/ht073195.ttl -o docs/example_ht073195.html
         pylode -i examples/examples/O149/ttl/o147.ttl -o docs/example_o147.html
         pylode -i examples/examples/TCH92/ttl/tch92.ttl -o docs/example_tch92.html
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
         BRANCH: gh-pages
         FOLDER: docs/
