name: Ontology Documentation CI

on: 
  push: 
      branches:
          - main
jobs:
  build:

    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Create Ontology Documentation 🔧
      run: |
         sudo apt-get install python3 python3-setuptools python3-pip -y
         sudo apt-get install gcc libpq-dev -y
         sudo apt-get install python3-dev python3-pip -y
         sudo apt-get install python3-venv python3-wheel -y
         sudo pip3 install wheel pylode==2.13.2 rdflib shapely
         pylode -i ontmodel/cuneiformontology.ttl -o docs/ontology.html
         pylode -i interlinks/cuneiformontology_interlinks.ttl -o docs/ontologyinterlinks.html
         pylode -i signlist/signlist.ttl -o docs/signlist.html
         pylode -i postagging/akkadian.ttl -o docs/postagging_akkadian.html
         pylode -i postagging/hittite.ttl -o docs/postagging_hittite.html
         pylode -i examples/HS1174/ttl/hs1174.ttl -o docs/example_hs1174.html
         pylode -i examples/HT073195/ttl/ht073195.ttl -o docs/example_ht073195.html
         pylode -i examples/O147/ttl/o147.ttl -o docs/example_o147.html
         pylode -i examples/TCH92/ttl/tch92.ttl -o docs/example_tch92.html
         mkdir docs/examples/
         mkdir docs/examples/hs1174/
         mkdir docs/examples/tch92/
         mkdir docs/examples/o147/
         cp -r examples/HS1174/images/ docs/examples/hs1174/images/ 
         cp -r examples/TCH92/images/ docs/examples/tch92/images/ 
         cp -r examples/O147/images/ docs/examples/o147/images/ 
         python3 docgeneration.py signlist/signlist.ttl docs/ https://situx.github.io/cuneiformontology/ cuneisignlist False
         python3 docgeneration.py examples/HS1174/transliteration/HS1174.atf.ttl docs/examples/ https://situx.github.io/cuneiformontology/ cuneiex
         python3 docgeneration.py examples/HS1174/ttl/HS1174_front.png.ttl docs/examples/ https://situx.github.io/cuneiformontology/ cuneiex
         python3 docgeneration.py examples/HS1174/ttl/HS1174_back.png.ttl docs/examples/ https://situx.github.io/cuneiformontology/ cuneiex
         python3 docgeneration.py examples/HS1174/mesh/HS1174_mesh.ttl docs/examples/ https://situx.github.io/cuneiformontology/ cuneiex
         python3 docgeneration.py examples/HT073195/transliteration/HT073195.atf.ttl docs/examples/ https://situx.github.io/cuneiformontology/ cuneiex
         python3 docgeneration.py examples/HT073195/ttl/HT073195_front.png.ttl docs/examples/ https://situx.github.io/cuneiformontology/ cuneiex
         python3 docgeneration.py examples/O147/transliteration/O147.atf.ttl docs/examples/ https://situx.github.io/cuneiformontology/ cuneiex
         python3 docgeneration.py examples/O147/ttl/O147_front.png.ttl docs/examples/ https://situx.github.io/cuneiformontology/ cuneiex
         python3 docgeneration.py examples/O147/ttl/O147_back.png.ttl docs/examples/ https://situx.github.io/cuneiformontology/ cuneiex
         python3 docgeneration.py examples/O147/ttl/O147_right.png.ttl docs/examples/ https://situx.github.io/cuneiformontology/ cuneiex
         python3 docgeneration.py examples/O147/ttl/O147_bottom.png.ttl docs/examples/ https://situx.github.io/cuneiformontology/ cuneiex
         python3 docgeneration.py examples/O147/mesh/O147_front_mesh.ttl docs/examples/ https://situx.github.io/cuneiformontology/ cuneiex
         python3 docgeneration.py examples/O147/mesh/O147_back_mesh.ttl docs/examples/ https://situx.github.io/cuneiformontology/ cuneiex
         python3 docgeneration.py examples/O147/transliteration/O147_textanno.ttl docs/examples/ https://situx.github.io/cuneiformontology/ cuneiex
         python3 docgeneration.py examples/TCH92//transliteration/TCH92.atf.ttl docs/examples/ https://situx.github.io/cuneiformontology/ cuneiex False
         python3 docgeneration.py examples/TCH92/ttl/TCH92_front.png.ttl docs/examples/ https://situx.github.io/cuneiformontology/ cuneiex
         python3 docgeneration.py examples/TCH92/ttl/TCH92_back.png.ttl docs/examples/ https://situx.github.io/cuneiformontology/ cuneiex
         python3 docgeneration.py examples/TCH92/mesh/TCH92_mesh.ttl docs/examples/ https://situx.github.io/cuneiformontology/ cuneiex
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
         BRANCH: gh-pages
         FOLDER: docs/
